# Generated by Django 4.2.5 on 2023-12-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Получатель заявок на обучение',
                'verbose_name_plural': 'Получатели заявок на обучение',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Notary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day', models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=15, null=True, verbose_name='Рабочие дни с')),
                ('end_day', models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=15, null=True, verbose_name='по')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Рабочее время с')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='по')),
                ('break_start', models.TimeField(blank=True, null=True, verbose_name='Перерыв с')),
                ('break_end', models.TimeField(blank=True, null=True, verbose_name='по')),
                ('start_day_off', models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=15, null=True, verbose_name='Выходные с')),
                ('end_day_off', models.CharField(blank=True, choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=15, null=True, verbose_name='по')),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('full_name_ru', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('full_name_ky', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('full_name_en', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город')),
                ('city_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город')),
                ('city_ky', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город')),
                ('city_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город')),
                ('status', models.CharField(choices=[('active', 'Действующий'), ('finished', 'Завершил деятельность')], default='active', max_length=50, verbose_name='Статус')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_ky', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(max_length=255, null=True, verbose_name='Адрес')),
                ('region', models.CharField(blank=True, null=True, verbose_name='Регион')),
                ('region_ru', models.CharField(blank=True, null=True, verbose_name='Регион')),
                ('region_ky', models.CharField(blank=True, null=True, verbose_name='Регион')),
                ('region_en', models.CharField(blank=True, null=True, verbose_name='Регион')),
                ('latitude', models.CharField(blank=True, default='Coordinates not defined', max_length=30, verbose_name='Широта')),
                ('longitude', models.CharField(blank=True, default='Coordinates not defined', help_text='Пустые поля координат заполняются автоматически.\n                                Автоматическое определение может давать некорректный результат,\n                                рекомендуется проверять полученные координаты.\n                                ', max_length=30, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Нотариус',
                'verbose_name_plural': 'Нотариусы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Получатель обращений граждан',
                'verbose_name_plural': 'Получатели обращений граждан',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('name_ky', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Доступная роль',
                'verbose_name_plural': 'Доступные роли',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NotaryFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('roles', models.ManyToManyField(blank=True, related_name='notary_flows', to='notary.role', verbose_name='Роли')),
            ],
            options={
                'verbose_name': 'Поток в нотариальный центр',
                'verbose_name_plural': 'Потоки в нотариальный центр',
            },
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('full_name_ru', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('full_name_ky', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('full_name_en', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('notary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='notary.notary', verbose_name='Нотариус')),
            ],
            options={
                'verbose_name': 'Ассистент',
                'verbose_name_plural': 'Ассистенты',
                'ordering': ['id'],
            },
        ),
    ]
