# Generated by Django 4.2.5 on 2023-11-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notary',
            name='latitude',
            field=models.CharField(blank=True, default='Coordinates not defined', max_length=30, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='longitude',
            field=models.CharField(blank=True, default='Coordinates not defined', help_text='Пустые поля координат заполняются автоматически.\n                                Автоматическое определение может давать некорректный результат,\n                                рекомендуется проверять полученные координаты.\n                                ', max_length=30, verbose_name='Долгота'),
        ),
    ]
