# Generated by Django 4.2.5 on 2023-11-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary', '0002_remove_notary_latitude_remove_notary_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notary',
            name='notary_coordinates',
        ),
        migrations.AddField(
            model_name='notary',
            name='latitude',
            field=models.CharField(blank=True, default='Coordinates not defined', max_length=30, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='notary',
            name='longitude',
            field=models.CharField(blank=True, default='Coordinates not defined', help_text='Пустые поля координат заполняются автоматически.\n                                Автоматическое определение может давать некорректный результат,\n                                рекомендуется проверять полученные координаты.\n                                ', max_length=30, verbose_name='Долгота'),
        ),
    ]
