# Generated by Django 4.2.5 on 2023-11-09 07:15

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('notary', '0003_remove_notary_notary_coordinates_notary_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notary',
            name='notary_coordinates',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, verbose_name='Координаты'),
        ),
    ]
