# Generated by Django 4.2.5 on 2023-11-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notary', '0004_notary_notary_coordinates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notary',
            name='notary_coordinates',
        ),
        migrations.AlterField(
            model_name='notary',
            name='end_day',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='end_day_en',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='end_day_ky',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='end_day_off',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='end_day_off_en',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='end_day_off_ky',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='end_day_off_ru',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='end_day_ru',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='start_day',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='Рабочие дни с'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='start_day_en',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='Рабочие дни с'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='start_day_ky',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='Рабочие дни с'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='start_day_off',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='Выходные с'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='start_day_off_en',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='Выходные с'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='start_day_off_ky',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='Выходные с'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='start_day_off_ru',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='Выходные с'),
        ),
        migrations.AlterField(
            model_name='notary',
            name='start_day_ru',
            field=models.CharField(blank=True, choices=[('Pon', 'Пон'), ('Vt', 'Вт'), ('Sr', 'Ср'), ('Ct', 'Чт'), ('Pt', 'Пт'), ('Sb', 'Сб'), ('Vs', 'Вс'), ('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], max_length=5, null=True, verbose_name='Рабочие дни с'),
        ),
    ]
