version: "3"
services:
  postgres:
    networks:
      - notpal_network

  api:
    expose:
      - 8017

    networks:
      - notpal_network

  nginx:
    container_name: notpal_nginx
    build: ./nginx
    ports:
      - 8001:8001
    depends_on:
      - api
    # volumes:
      # server
      # - /home/team3/geoconsult/static_root:/static_root
      # - /home/team3/geoconsult/media_storage:/media_storage

      # local
      # - ./static_root:/static_root
      # - ./media_storage:/media_storage

    networks:
      - notpal_network

  redis:
    container_name: notpal_redis
    image: redis:7.2.2-alpine
    expose:
      - 6379

    networks:
      - notpal_network
  
  celery:
    container_name: notpal_celery
    build:
      context: ./backend
    command: celery -A core worker -l INFO
    depends_on:
      - redis
      - api
    env_file:
      - ./backend/.env

    networks:
      - notpal_network

volumes:
    pgdata:
    static_root:
    media_storage:

networks:
  notpal_network:
    external: true
