# Generated by Django 4.2.5 on 2023-12-08 04:43

from django.db import migrations, models
import django.db.models.deletion
import ed_centres.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('thesis', models.TextField(verbose_name='Тезис')),
                ('thesis_ru', models.TextField(null=True, verbose_name='Тезис')),
                ('thesis_ky', models.TextField(null=True, verbose_name='Тезис')),
                ('thesis_en', models.TextField(null=True, verbose_name='Тезис')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ed_centres.models.center_info, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Обр. центры - информация',
                'verbose_name_plural': 'Обр. центры - информация',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='CenterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Формулировка')),
                ('text_ru', models.TextField(null=True, verbose_name='Формулировка')),
                ('text_ky', models.TextField(null=True, verbose_name='Формулировка')),
                ('text_en', models.TextField(null=True, verbose_name='Формулировка')),
            ],
            options={
                'verbose_name': 'Обр. центры - задача',
                'verbose_name_plural': 'Обр. центры - задачи',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EducationalMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Обр. центры - учебный материал',
                'verbose_name_plural': 'Обр. центры - учебные материалы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('full_name_ky', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('text', models.TextField(verbose_name='Текст')),
                ('text_ru', models.TextField(null=True, verbose_name='Текст')),
                ('text_ky', models.TextField(null=True, verbose_name='Текст')),
                ('text_en', models.TextField(null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to=ed_centres.models.center_management, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Обр. центры - руководитель',
                'verbose_name_plural': 'Обр. центры - руководство',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Раздел')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Раздел')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Раздел')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Обр. центры - учебный план',
                'verbose_name_plural': 'Обр. центры - учебные планы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TeachingStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('full_name_ky', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('position_ru', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_ky', models.CharField(max_length=255, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(max_length=255, null=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Обр. центры - преподаватель',
                'verbose_name_plural': 'Обр. центры - преподаватели',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Контент')),
                ('content_ru', models.TextField(null=True, verbose_name='Контент')),
                ('content_ky', models.TextField(null=True, verbose_name='Контент')),
                ('content_en', models.TextField(null=True, verbose_name='Контент')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='ed_centres.studyplan', verbose_name='Учебный план')),
            ],
            options={
                'verbose_name': 'Обр. центры - учебная дисциплина',
                'verbose_name_plural': 'Обр. центры - учебные дисциплины',
                'ordering': ('id',),
            },
        ),
    ]
