# Generated by Django 4.2.5 on 2023-11-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='main_image',
            new_name='image',
        ),
    ]
