# Generated by Django 4.2.5 on 2023-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Рекомендовать'),
        ),
    ]
