# Generated by Django 4.2.5 on 2023-10-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закрепленные'),
        ),
    ]
