# Generated by Django 4.2.5 on 2023-11-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Виден на сайте'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Телефон'),
        ),
    ]
