# Generated by Django 4.2.5 on 2023-10-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_news_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AlterField(
            model_name='news',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закрепить'),
        ),
    ]
