# Generated by Django 4.2.5 on 2023-11-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_main_image_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='main_image',
        ),
    ]
